import { useState, useEffect } from "react";
import { listDept, delDept, addDept, updateDept } from "../../../../api/system/dept";
import DepartmentModal from "./DeptModal";
import { ChevronDown, ChevronRight } from "lucide-react";
import { useToast, toast } from "../../../../components/alert/Toast";
import ManagementButtons from "../../../../components/ui/admin/ManagmentButtons";
import OperationButtons from "../../../../components/ui/admin/OperationButtons";
import ConfirmDeleteModal from "../../../../components/modal/ConfirmDeleteModal";
import { usePermission } from "../../../../utils/usePermisssion";

interface Department {
  deptId: number;
  parentId: number;
  deptName: string;
  orderNum: number;
  status: string;
  createTime: string;
  ancestors: string;
  leader: string;
  phone: string;
  email: string;
  delFlag: string;
  children?: Department[];
}

const DepartmentPage = () => {
  const { showToast } = useToast();
  //Permission based rendering buttons
  const canAdd = usePermission('system:dept:add');
  const canDelete = usePermission('system:dept:remove');
  const canEdit = usePermission('system:dept:edit');
  const showOperateColumn = canEdit || canDelete || canAdd;

  const [expandedIds, setExpandedIds] = useState<Set<number>>(new Set());
  const [showModal, setShowModal] = useState(false);
  const [selectedParentId, setSelectedParentId] = useState<number>(0);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [deleteDeptId, setDeleteDeptId] = useState<number | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);
  const [editingDept, setEditingDept] = useState<Department | null>(null);

  const fetchDepartments = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await listDept();
      const data = Array.isArray(res.data) ? res.data : res.data?.data || [];
      const tree = buildDeptTree(data);
      setDepartments(tree);
    } catch (err: any) {
      setError(err.message || "Failed to load departments");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDepartments();
  }, []);

  function buildDeptTree(list: Department[]): Department[] {
    const map = new Map<number, Department>();
    const roots: Department[] = [];

    // Initialize map and children arrays
    list.forEach(item => {
      map.set(item.deptId, { ...item, children: [] });
    });

    // Build the tree
    list.forEach(item => {
      const node = map.get(item.deptId)!;
      if (item.parentId === 0) {
        roots.push(node);
      } else {
        const parent = map.get(item.parentId);
        if (parent) {
          parent.children!.push(node);
        }
      }
    });

    return roots;
  }

  const handleAddDepartment = async (newDept: Department) => {
    try {
      // Remove deptId and other fields that should be generated by backend
      const apiData = {
        parentId: newDept.parentId,
        deptName: newDept.deptName,
        orderNum: newDept.orderNum,
        leader: newDept.leader || '',
        phone: newDept.phone || '',
        email: newDept.email || '',
        status: newDept.status,
        ancestors: newDept.ancestors || '',
        delFlag: newDept.delFlag || '0'
      };

      await addDept(apiData);
      showToast(toast.success("Department added successfully."));
      fetchDepartments(); // Refresh the data from API
    } catch (err: any) {
      showToast(toast.error(err?.message || "Failed to add department."));
    }
  };

  const toggleExpand = (id: number) => {
    setExpandedIds((prev) => {
      const newSet = new Set(prev);
      newSet.has(id) ? newSet.delete(id) : newSet.add(id);
      return newSet;
    });
  };

  const handleUpdateDepartment = async (updatedDept: Department) => {
    try {
      // Format data for API update
      const apiData = {
        deptId: updatedDept.deptId,
        parentId: updatedDept.parentId,
        deptName: updatedDept.deptName,
        orderNum: updatedDept.orderNum,
        leader: updatedDept.leader || '',
        phone: updatedDept.phone || '',
        email: updatedDept.email || '',
        status: updatedDept.status,
        ancestors: updatedDept.ancestors || '',
        delFlag: updatedDept.delFlag || '0'
      };

      await updateDept(apiData);
      showToast(toast.success("Department updated successfully."));
      fetchDepartments(); // Refresh the data from API
    } catch (err: any) {
      showToast(toast.error(err?.message || "Failed to update department."));
    }
  };

  const handleDeleteDepartment = async () => {
    if (deleteDeptId === null) return;
    setDeleteLoading(true);
    try {
      await delDept(String(deleteDeptId));
      showToast(toast.success("Department deleted successfully."));
      fetchDepartments();
    } catch (err: any) {
      showToast(toast.error(err?.message || "Failed to delete department."));
    } finally {
      setDeleteLoading(false);
      setDeleteDeptId(null);
    }
  };

  const handleModalSubmit = async (dept: Department) => {
    if (editingDept) {
      await handleUpdateDepartment({ ...editingDept, ...dept });
    } else {
      await handleAddDepartment(dept);
    }
    setShowModal(false);
    setEditingDept(null);
  };

  const renderDepartments = (items: Department[], level = 0): JSX.Element[] => {
    return items.flatMap((dept) => {
      const isExpanded = expandedIds.has(dept.deptId);
      const hasChildren = dept.children && dept.children.length > 0;
      const padding = level * 20;
      return [
        <tr key={dept.deptId} className="text-sm hover:bg-slate-50 text-center">
          <td className="p-3 border-b border-gray-300 text-left" style={{ paddingLeft: `${padding}px` }}>
            {hasChildren && (
              <button
                onClick={() => toggleExpand(dept.deptId)}
                className="mr-2">
                {isExpanded ? <ChevronDown size={20} /> : <ChevronRight size={20} />}
              </button>
            )}
            {dept.deptName}
          </td>
          <td className="p-3 border-b border-gray-300">{dept.orderNum}</td>
          <td className="p-3 border-b border-gray-300">
            <span className={`px-3 py-1 rounded-full text-xs font-medium transition-colors ${dept.status === "0"
                ? "bg-green-100 text-green-800 hover:bg-green-200"
                : "bg-red-100 text-red-800 hover:bg-red-200"
              }`}>
              {dept.status === "0" ? "Active" : "Inactive"}
            </span>
          </td>
          <td className="p-3 border-b border-gray-300">{dept.createTime}</td>
          {showOperateColumn && (
            <td className="p-3 border-b border-gray-300">
              <div className="flex justify-center gap-2">
                <OperationButtons
                  size="sm"
                  addTitle="Add Child Department"
                  {...(canAdd ? { onAdd: () => { setSelectedParentId(dept.deptId); setShowModal(true); setEditingDept(null); } } : {})}
                  editTitle="Edit Department"
                  {...(canEdit ? { onEdit: () => { setEditingDept(dept); setShowModal(true); } } : {})}
                  deleteTitle="Delete Department"
                  {...(canDelete ? { onDelete: () => setDeleteDeptId(dept.deptId) } : {})}
                />
              </div>
            </td>
          )}
        </tr>,
        ...(isExpanded && dept.children ? renderDepartments(dept.children, level + 1) : [])
      ];
    });
  };

  return (
    <div className="rounded-md bg-gray-200 flex-1 m-4 mt-4">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center bg-white p-4 justify-between rounded-md mb-4">
        <h1 className="text-lg font-semibold">Department Management</h1>
        <div className="flex flex-wrap gap-2">
          <ManagementButtons
            size="md"
            {...(canAdd ? { addLabel: "Add Department", onAdd: () => { setSelectedParentId(0); setShowModal(true); } } : {})}
            onRefresh={() => fetchDepartments()}
          />
        </div>
      </div>
      {loading ? (
        <div className="p-4 text-center">Loading departments...</div>
      ) : error ? (
        <div className="p-4 text-center text-red-500">{error}</div>
      ) : (
        <div className="flex items-center bg-white  justify-between rounded-md mb-4">
          <table className="w-full border border-collapse text-sm">
            <thead>
              <tr className="bg-gray-100 text-center">
                <th className="p-3 border-b border-gray-300">Department Name</th>
                <th className="p-3 border-b border-gray-300">Order</th>
                <th className="p-3 border-b border-gray-300">Status</th>
                <th className="p-3 border-b border-gray-300">Creation Time</th>
                {showOperateColumn && (<th className="p-3 border-b border-gray-300">Operate</th>)}
              </tr>
            </thead>
            <tbody>
              {renderDepartments(departments.slice())}
            </tbody>
          </table>
        </div>)}
      <DepartmentModal
        isOpen={showModal}
        onClose={() => { setShowModal(false); setEditingDept(null); }}
        onSubmit={handleModalSubmit}
        departments={departments}
        initialParentId={selectedParentId}
        editingDept={editingDept}
      />
      <ConfirmDeleteModal
        isOpen={deleteDeptId !== null}
        onClose={() => setDeleteDeptId(null)}
        onConfirm={handleDeleteDepartment}
        title="Delete Department"
        message="Are you sure you want to delete this department? This action cannot be undone."
        isLoading={deleteLoading}
      />
    </div>
  );
};

export default DepartmentPage;
